FROM node:14 as build
WORKDIR /usr/src/app
COPY package.json /usr/src/app
RUN npm install 
COPY . /usr/src/app
RUN npm run build


FROM nginx:1.12-alpine
EXPOSE 80
COPY --from=build /usr/src/app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d


CMD [ "nginx", "-g", "daemon off;" ]

