version: "3.9"

services:
  socket:
    image: nurettinsenbackend/socket
    ports:
      - 6500:6500
    tty: true
    env_file: socket/.env
    depends_on:
      - frontend

    networks:
      - webapp

  backend:
    image: nurettinsenbackend/server
    depends_on:
      - mongo
      - redis
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    env_file: ./server/.env
    environment:
      - DB_HOST=mongo
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=Blog
      - DB_PORT=27017
      - NODE_ENV=production

    ports:
      - 5000:5000

    networks:
      - webapp

    secrets:
      - db_password

  frontend:
    image: nurettinsenbackend/client

    ports:
      - 3000:3000
    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true

    networks:
      - webapp
    depends_on:
      - backend

  mongo:
    image: mongo

    volumes:
      - db-data:/var/lib/mongo/data
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

    networks:
      - webapp

    secrets:
      - db_password

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

    command: redis-server --save 20 1 --loglevel warning --requirepass nopass
    networks:
      - app

  nginx:
    image: nginx:1.21.5-alpine

    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
    depends_on:
      - frontend
      - backend
    networks:
      - webapp

  certbot:
    image: certbot/certbot:v1.9.0
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email nurie487@gmail.com --agree-tos --no-eff-email --force-renewal -d devat.xyz  -d www.devat.xyz

networks:
  webapp:
    driver: overlay
    # attachable: true
    # external: false

secrets:
  db_password:
    file: db_password.txt

volumes:
  db-data:
  certbot-etc:
  certbot-var:
  web-root:
