version: "3.9"

services:



  mongo:

    image: mongo
   
    volumes:
      - db-data:/var/lib/mongo/data
    ports:
      - 27017:27017
    env_file: ./server/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
   
    networks:
      - webapp

    secrets:
      - db_password
      
  
  

  backend:
    
    image: nurettinsenbackend/social-media
    
    depends_on:
      - mongo

    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
 
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s    
    env_file: ./server/.env
    environment:
      - DB_HOST=mongo
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=Blog
      - DB_PORT=27017
      - NODE_ENV=production
    
    ports:
      - 6868:5000

   
    networks:
      - webapp

    secrets:
      - db_password
      

networks:
  webapp:
    driver: overlay
    # attachable: true
    # external: false

secrets:
  db_password:
    file: db_password.txt


volumes:
  db-data:



# dersı dınledın yarın bı genel db ve backend olarak calıstır zaten daha sonra docker huba yukledıgın clıent ve backend socket repository uzerınden yaml dosyana
# clientıda  ve  socketı de ekle çalıştırmaya calıs daha sonra yotuubden vıdeo felan ızlersın okadar 